PREFIX rxno: <http://purl.obolibrary.org/obo/RXNO_>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?rxno_class ?rdfs_label
WHERE {
        ?rxno_class rdf:type owl:Class.
        BIND(ucase(str(?rxno_class)) AS ?rxno_str).
        FILTER(contains(?rxno_str, "RXNO")).     
}

# classes RXNO: in rxno ontology
